### ISSUE TITLE
"Class \"Binaryk\\LaravelRestify\\Tests\\Fixtures\\User\\User\" not found

### ISSUE THREAD

**Issue by mahmoudawadeen** [binaryk/laravel-restify#519]
https://github.com/BinarCode/laravel-restify/blob/d0cff087b7212d66fdfabce479bd3de9f9e40f7f/src/Http/Controllers/Auth/VerifyController.php#L16
```php
/** * @var User $user */
$user = config('restify.auth.user_model')::query()->findOrFail($id); 
```

**Comment by binaryk** [comment]
Thanks @mahmoudawadeen

**Comment by mahmoudawadeen** [comment]
> Thanks @mahmoudawadeen 

Happy to help.


Would be great if you can also take a look on https://github.com/BinarCode/laravel-restify/issues/524 

It's from my work account :)

**Comment by binaryk** [comment]
Fixed, thank you!
