### ISSUE TITLE
Docs for media is missing a function call to store the media

### ISSUE THREAD

**Issue by mahmoudawadeen** [binaryk/laravel-restify#527]
# Existing 
https://github.com/BinarCode/laravel-restify/blob/f87b81b40f357608f9af2f7ee5a76dcf240b62d6/docs-v2/content/en/api/fields.md#L308
# Issue
According to the docs for the [media library](https://spatie.be/docs/laravel-medialibrary/v9/introduction), you need to use one of the "finishing methods" to store the media. Just calling `addMediaFromRequest` doesn't store the file.
# Suggested
```
        $post->addMediaFromRequest('file')
            ->toMediaCollection();
```

**Comment by binaryk** [comment]
Updated! Thank you!
