### ISSUE TITLE
Issue in relationship

### ISSUE THREAD

**Issue by wasiqaftab** [binaryk/laravel-restify#538]
HI sorry a wired bug in relationship or may be its me i am scratching my head from last 2 days but didnt get around it. please see the code 
` return [
            'contactsUser' => HasMany::make('userfriends', UserRepository::class),
        ];`

but the  result which i get from index function just one record relationship recorded. can you please tell me what i am doing wrong i see the repo keys etc all are okay. userfriends has a relation in contact model @binaryk can you please check it

**Comment by arthurkirkosa** [comment]
I'd recommend you use the same key in the Repository as the name of the function in your User model.

`return [ 'userfriends' => HasMany::make('userfriends', UserRepository::class)];` if you relation in User is `public function userfriends(): HasMany`

**Comment by wasiqaftab** [comment]
@arthurkirkosa i am doing same please see the snippets

Table structure is 

users have user id as uuid 
contacts table have 
**user_id** as uuid and **friend_id** as uuid 

1. User Model

` public function userfriends(): HasMany
    {
        return $this->hasMany(Contact::class,'friend_id', 'id');
    }`

2. ContactsRepository Relation

Key on contacts repository is `    public static string $uriKey = 'contacts';` 

` public static function related(): array
    {
        return [
            'userfriends' => HasMany::make('userfriends', UserRepository::class),
        ];
}`

3. Contact Model

` public function userfriends(): BelongsTo
    {
        return $this->belongsTo(User::class, 'friend_id');
    }`

API call if is like that 

`{{host}}/api/restify/contacts?related=userfriends`

Result i am expecting is all friend_ids with relation but now i am getting error of un defined function maps 

` "message": "Call to undefined method App\\Models\\User::map()",`

Please guide am i doing something wrong

**Comment by wasiqaftab** [comment]
Also if i use belongsTo relation like that 
` return [
            'userRelationship' => BelongsTo::make('userfriends', UserRepository::class),
        ];`

it will only return first record as relation output something like that

![Screenshot 2023-02-14 at 9 45 19 pm](https://user-images.githubusercontent.com/3602917/218870255-7445fc9d-ec51-4fdf-808f-c1ec8a823f85.png)

Please guide as it just show relation for first record

**Comment by arthurkirkosa** [comment]
Yes, as Contact has a BelongTo with User, that's the relation you have to use in your ContactRepository as well.

Because a Contact Belongs To a User, it's normal for you to have just one item of User loaded with that Contact

If you what the full list of contacts start from the User repo 
`GET /api/restify/users?related=userfriends`

For clarity I would rename the methods in each model to the corresponding entity

```
// User

public function contacts(): HasMany {}
// or
public function friends(): HasMany {}

// Contact

public function user(): BelongsTo {}
// or
public function friend(): BelongsTo {}
```

Naming them in singular and plural would outline how many object I should receive when using the relation in the code
