### ISSUE TITLE
nullable belongsto relationship

### ISSUE THREAD

**Issue by BerndKammlott** [binaryk/laravel-restify#544]
Hi,

if i define a blongsto relationship in fields, i have to fill this field in the request, otherwise i get a "no query results for model" exeption. however, this relation is optional. i can not see how to make this field optional, restify always want to resolve the relation. Expeption is thrown in BelongsTo -> fillAttribute -> firstOrFail

![Screenshot 2023-03-03 104902](https://user-images.githubusercontent.com/5768530/222689391-437c3716-e2ee-4b00-adbd-139c23a454e8.png)
![Screenshot 2023-03-03 104933](https://user-images.githubusercontent.com/5768530/222689396-3d52c3ab-94fd-4dbc-92ae-baa512a6b106.png)
![Screenshot 2023-03-03 104809](https://user-images.githubusercontent.com/5768530/222689399-38313816-a746-4023-ae65-1689fdf61899.png)

**Comment by binaryk** [comment]
Hi @BerndKammlott , as you can see in the documentation, Restify uses BelongsTo only as a related field, it's used for relationships not as a field.

Docs for fields: https://restify.binarcode.com/api/fields
Docs for relationships: https://restify.binarcode.com/api/relations#belongsto--morphone
