### ISSUE TITLE
Docs say you should use "Post" on "Getters", but you need to use a "Get"

### ISSUE THREAD

**Issue by HakuG** [binaryk/laravel-restify#554]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/5514073/231831382-22f24e9f-1107-4e18-8dca-8b0268781850.png">
<img width="699" alt="image" src="https://user-images.githubusercontent.com/5514073/231831463-83e8671e-4ae0-4e7a-9ebb-75102856278b.png">

Calling it with "Post" causes it to fail in RestifyRequest.php. 

```
$eagerField = $parentRepository::collectRelated()
            ->forEager($this)
            ->first(fn (EagerField $field, $key) => $field->getAttribute() === $this->route('repository'));
       
        if (is_null($eagerField)) {
            abort(403, 'Eager field missing from the parent ['.$this->route('parentRepository').'] related fields.');
        }

```

**Comment by binaryk** [comment]
Fixed: https://github.com/BinarCode/laravel-restify/pull/555

**Comment by binaryk** [comment]
It should be a "GET" request, not "POST".
