### ISSUE TITLE
API quietly fails if policy does not exist

### ISSUE THREAD

**Issue by HakuG** [binaryk/laravel-restify#561]
API is quiet if the policy does not exist while capturing on a related element. 

```
public static function related(): array
    {
        return [
            'conversation' => BelongsTo::make('conversation', ConversationRepository::class),
            'attachments' => HasMany::make('attachments', AttachmentRepository::class)
        ];
    }

```

AttachmentRepository didn't have an associated AttachmentPolicy, so it wasn't fetching attachments. It wasn't until I added a policy that the route started working. 

Would prefer that it fails with some error to notify the user of the necessary additional configuration.

**Comment by binaryk** [comment]
I would debate this. Since `Attachments` is a `hasMany` relationship, you might have some attachments you don't have access to, so you want to leverage to the policy to filter them out instead of failing the main repository request.

**Comment by HakuG** [comment]
Agreed, but if there isn't a policy to leverage, it should error out, right? In this case, the policy file didn't exist, so it quietly fails.
