### ISSUE TITLE
Run command: route:cache (Error)

### ISSUE THREAD

**Issue by ttungbmt** [binaryk/laravel-restify#566]
![image](https://github.com/BinarCode/laravel-restify/assets/12232155/8efa2aab-5f92-4027-9757-7c8e144d0040)
Duplicate route name
![image](https://github.com/BinarCode/laravel-restify/assets/12232155/e727c769-2689-4981-aa2a-4c185c6adbba)

**Comment by chantouchsek** [comment]
Hope this will fix asap.
