### ISSUE TITLE
I installed the package and followed the instructions and got an error 404

### ISSUE THREAD

**Issue by trihai306** [binaryk/laravel-restify#577]
![image](https://github.com/BinarCode/laravel-restify/assets/68975387/1b5e6d39-5e07-4481-a593-e48d0f3ef7f6)

**Comment by binaryk** [comment]
Please make sure you have `http://api.test`. And use the `application/json` header: 

![image](https://github.com/BinarCode/laravel-restify/assets/6833714/1efd5749-e87b-40dc-a290-0eaf8c184dbc)
