### ISSUE TITLE
unwarranted error in json

### ISSUE THREAD

**Issue by trihai306** [binaryk/laravel-restify#578]
![image](https://github.com/BinarCode/laravel-restify/assets/68975387/0bdfa470-5be0-4487-9802-f8cebbd87645)
![image](https://github.com/BinarCode/laravel-restify/assets/68975387/6556ddde-d66a-4336-8eb8-e0b712581baf)

**Comment by binaryk** [comment]
Make sure you have `application/json` as Accept Header in postman
![image](https://github.com/BinarCode/laravel-restify/assets/6833714/043ae3e3-053b-491f-8c23-8148e584ef99)
