### ISSUE TITLE
RestifyJs can only be accessed if authenticated.

### ISSUE THREAD

**Issue by rizkyseptiawan** [binaryk/laravel-restify#593]
I tried using restifyjs, but the _restify.api.restifyjs.setup_ route is only accessible if authenticated. It shouldn't be like that. After I did some checking. I am using auth:sanctum as middleware. It looks like the problem is there. Because there is no 'auth:sanctum' in withoutMiddleware.

**src/Bootstrap/RoutesDefinition.php**
```
    public function once(): void
    {
        ...............

        // RestifyJS
        Route::get('/restifyjs/setup', RestifyJsSetupController::class)->withoutMiddleware(
            RestifySanctumAuthenticate::class,
        )->name('restifyjs.setup');
    }
```

**Comment by binaryk** [comment]
Fixed https://github.com/BinarCode/laravel-restify/releases/tag/8.3.2
